export type EventSpotSeed = {
  id: string;
  country: string;
  city: string;
  name: string;
  lat: number;
  lng: number;
  spotKind: "permanent" | "limited";
  rewardKind: "gold_seedling" | "mixed";
  rewardSummary: string;
  startAt: number;
  endAt: number;
  cooldownNote: string;
  eligibilityNote: string;
  coordinateNote: string;
  verificationStatus: "official";
  sourceTitle: string;
  sourceUrl: string;
  lastVerifiedAt: number;
};

const seconds = (value: string) => Math.floor(Date.parse(value) / 1000);
const officialHelp = "https://niantic.helpshift.com/hc/en/23-pikmin-bloom/faq/3623-special-spot/?app_id=niantic_app_20191018003855906-90e74c8b4bfbc25&faq_id=niantic_faq_20210714025851089-b1376ee217dca25&is_preview=false&is_sdkx=false&language=en&platform_id=niantic_platform_20180726175230075-13b9ec875546270&platform_type=web";
const verified = seconds("2026-08-22T00:00:00Z");
const verified2 = seconds("2026-08-21T00:00:00Z");

// Coordinates identify the venue or published Special Spot area.  They are
// deliberately curated rather than inferred from scanner data; the game UI is
// still authoritative for the final interaction radius.
export const EVENT_SPOT_SEED: EventSpotSeed[] = [
  {
    id: "jp-nintendo-tokyo", country: "日本", city: "東京", name: "Nintendo TOKYO",
    lat: 35.661989, lng: 139.698784, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅色照片鈕扣徽章飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "澀谷 PARCO 6F 場館座標", verificationStatus: "official",
    sourceTitle: "Pikmin Bloom Help Center — Special Spot", sourceUrl: officialHelp, lastVerifiedAt: verified,
  },
  {
    id: "jp-nintendo-osaka", country: "日本", city: "大阪", name: "Nintendo OSAKA",
    lat: 34.70135, lng: 135.497, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅色照片鈕扣徽章飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "大丸梅田店 13F 場館座標", verificationStatus: "official",
    sourceTitle: "Pikmin Bloom Help Center — Special Spot", sourceUrl: officialHelp, lastVerifiedAt: verified,
  },
  {
    id: "jp-nintendo-kyoto", country: "日本", city: "京都", name: "Nintendo KYOTO",
    lat: 35.003075, lng: 135.768344, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅色照片鈕扣徽章飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "京都高島屋 S.C. 7F 場館座標", verificationStatus: "official",
    sourceTitle: "Pikmin Bloom Help Center — Special Spot", sourceUrl: officialHelp, lastVerifiedAt: verified,
  },
  {
    id: "jp-nintendo-fukuoka", country: "日本", city: "福岡", name: "Nintendo FUKUOKA",
    lat: 33.590059, lng: 130.400865, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅色照片鈕扣徽章飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "福岡 PARCO 場館座標", verificationStatus: "official",
    sourceTitle: "Nintendo FUKUOKA Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/news/nov25-nintendostore", lastVerifiedAt: verified,
  },
  {
    id: "jp-nintendo-museum", country: "日本", city: "宇治", name: "Nintendo Museum",
    lat: 34.892904, lng: 135.784188, spotKind: "permanent", rewardKind: "mixed",
    rewardSummary: "金色花苗（花牌飾品／金色禮物貼紙飾品）", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需預約及購票入館；以遊戲顯示為準",
    coordinateNote: "Nintendo Museum 場館座標", verificationStatus: "official",
    sourceTitle: "Nintendo Museum Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/news/oct24-nintendomuseum", lastVerifiedAt: verified,
  },
  {
    id: "jp-niantic-park", country: "日本", city: "東京", name: "Niantic Park（明治公園）",
    lat: 35.675424, lng: 139.71291, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "金色禮物貼紙飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "明治公園 Special Spot 場館座標", verificationStatus: "official",
    sourceTitle: "Niantic Park Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/news/nov24-nianticpark", lastVerifiedAt: verified,
  },
  {
    id: "jp-miyajima-terrace", country: "日本", city: "廿日市", name: "宮島服務區 Pikmin Terrace",
    lat: 34.365319, lng: 132.318022, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "紅色照片鈕扣徽章／運勢飾品皮克敏金色花苗", startAt: seconds("2026-05-01T00:00:00+09:00"), endAt: seconds("2027-03-31T23:59:59+09:00"),
    cooldownNote: "活動期間每個 Special Spot 限 1 次", eligibilityNote: "宮島服務區（下行線）戶外區域；以遊戲顯示為準",
    coordinateNote: "活動區域入口座標；兩個金盆 Spot 的實際位置請依遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "宮島服務區 Pikmin Terrace 官方活動公告", sourceUrl: "https://pikminbloom.com/zh/news/april26-miyajimasa", lastVerifiedAt: verified,
  },

  // ---- 日本・京都「とっておきの京都」明信片健走（Postcard Walk，2024-11-06 起，官方公告尚無結束日期） ----
  {
    id: "jp-kyoto-keihoku-joshokoji", country: "日本", city: "京都", name: "常照皇寺（京北）",
    lat: 35.166944, lng: 135.635278, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入京北區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」京北區域 5 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "常照皇寺場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-keihoku-yamaguni", country: "日本", city: "京都", name: "山國神社（京北）",
    lat: 35.159400, lng: 135.616700, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入京北區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」京北區域 5 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "山國神社場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-keihoku-kinkazan-hosenji", country: "日本", city: "京都", name: "金輪寺（京北）",
    lat: 35.161000, lng: 135.617000, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入京北區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」京北區域 5 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "金輪寺（京北）場館座標，座標精度較低，強烈建議以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-keihoku-woody", country: "日本", city: "京都", name: "道の駅 ウッディー京北",
    lat: 35.152000, lng: 135.598000, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入京北區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」京北區域 5 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "道の駅ウッディー京北場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-keihoku-kurodaya", country: "日本", city: "京都", name: "黒田屋（京北）",
    lat: 35.150000, lng: 135.600000, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入京北區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」京北區域 5 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "黒田屋（京北）場館座標，座標精度較低，強烈建議以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-ohara-sanzenin", country: "日本", city: "京都", name: "三千院（大原）",
    lat: 35.121667, lng: 135.827778, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入大原區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」大原區域 3 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "三千院場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-ohara-jakkoin", country: "日本", city: "京都", name: "寂光院（大原）",
    lat: 35.126944, lng: 135.816944, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入大原區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」大原區域 3 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "寂光院場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-ohara-businfo", country: "日本", city: "京都", name: "京都巴士大原案內所",
    lat: 35.119700, lng: 135.832400, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入大原區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」大原區域 3 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "京都巴士大原案內所場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-takao-jingoji", country: "日本", city: "京都", name: "神護寺（高雄）",
    lat: 35.056389, lng: 135.672500, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入高雄區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」高雄區域 3 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "神護寺場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-takao-hiraoka-hachimangu", country: "日本", city: "京都", name: "平岡八幡宮（高雄）",
    lat: 35.050800, lng: 135.665600, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入高雄區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」高雄區域 3 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "平岡八幡宮場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-takao-shigetsukyo", country: "日本", city: "京都", name: "指月橋（高雄）",
    lat: 35.054000, lng: 135.673000, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入高雄區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」高雄區域 3 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "指月橋（高雄）場館座標，座標精度較低，強烈建議以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-yamashina-ooishi", country: "日本", city: "京都", name: "大石神社（山科）",
    lat: 34.984700, lng: 135.816700, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入山科區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」山科區域 3 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "大石神社場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-yamashina-origami-inari", country: "日本", city: "京都", name: "折上稲荷神社（山科）",
    lat: 34.997500, lng: 135.820600, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入山科區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」山科區域 3 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "折上稲荷神社場館座標，座標精度較低，強烈建議以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-yamashina-zuikoin", country: "日本", city: "京都", name: "瑞光院（山科）",
    lat: 34.973600, lng: 135.824400, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入山科區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」山科區域 3 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "瑞光院（山科）場館座標，座標精度較低，強烈建議以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-saikyo-jizoin", country: "日本", city: "京都", name: "地蔵院・竹の寺（西京）",
    lat: 34.990800, lng: 135.693100, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入西京區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」西京區域 5 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "地蔵院（竹の寺）場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-saikyo-jojuji", country: "日本", city: "京都", name: "浄住寺（西京）",
    lat: 34.992500, lng: 135.692800, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入西京區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」西京區域 5 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "浄住寺場館座標，座標精度較低，強烈建議以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-saikyo-shoboji", country: "日本", city: "京都", name: "正法寺（西京）",
    lat: 34.949400, lng: 135.688900, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入西京區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」西京區域 5 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "正法寺（西京・大原野）場館座標，座標精度較低，強烈建議以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-saikyo-otoshi", country: "日本", city: "京都", name: "大歳神社（西京）",
    lat: 34.999700, lng: 135.683600, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入西京區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」西京區域 5 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "大歳神社（松尾）場館座標，座標精度較低，強烈建議以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-saikyo-bamboo-park", country: "日本", city: "京都", name: "京都市洛西竹林公園（西京）",
    lat: 34.961400, lng: 135.670600, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入西京區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」西京區域 5 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "京都市洛西竹林公園場館座標，座標精度較低，強烈建議以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-fushimi-nagao-tenmangu", country: "日本", city: "京都", name: "長尾天満宮（伏見）",
    lat: 34.944000, lng: 135.798600, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入伏見區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」伏見區域 4 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "長尾天満宮場館座標，座標精度較低，強烈建議以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-fushimi-gokonomiya", country: "日本", city: "京都", name: "御香宮神社（伏見）",
    lat: 34.936700, lng: 135.762800, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入伏見區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」伏見區域 4 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "御香宮神社場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-fushimi-fujinomori", country: "日本", city: "京都", name: "藤森神社（伏見）",
    lat: 34.958300, lng: 135.773600, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入伏見區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」伏見區域 4 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "藤森神社場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },
  {
    id: "jp-kyoto-fushimi-kinsatsugu", country: "日本", city: "京都", name: "金札宮（伏見）",
    lat: 34.939400, lng: 135.761400, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "地區代表明信片＋京都府花「石竹（撫子）」花蜜；進入伏見區域另有 3000 步任務可得紅色禮物貼紙金色花苗",
    startAt: seconds("2024-11-06T00:00:00+09:00"), endAt: 0,
    cooldownNote: "每個 Special Spot 限領取明信片 1 次；3000 步任務每區域限 1 次", eligibilityNote: "「とっておきの京都」伏見區域 4 個 Spot 之一；以遊戲顯示為準",
    coordinateNote: "金札宮場館座標，座標精度較低，強烈建議以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "とっておきの京都 明信片健走官方公告", sourceUrl: "https://pikminbloom.com/en/news/nov24-totteokinokyoto", lastVerifiedAt: verified2,
  },

  // ---- 日本・京都（已結束限時活動，保留歷史紀錄，預設隱藏） ----
  {
    id: "jp-kyoto-sanga-stadium", country: "日本", city: "京都", name: "Sanga Stadium by KYOCERA",
    lat: 34.985800, lng: 135.564400, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "紅色鑰匙圈飾品皮克敏金色花苗＋活動限定明信片",
    startAt: seconds("2026-02-06T00:00:00+09:00"), endAt: seconds("2026-06-07T23:59:59+09:00"),
    cooldownNote: "活動期間每位玩家限領取 1 次", eligibilityNote: "京都紫光俱樂部主場；已於 2026-06-07 結束，僅供歷史查詢",
    coordinateNote: "Sanga Stadium by KYOCERA 場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "Sanga Stadium Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/news/feb26-kyotosanga", lastVerifiedAt: verified2,
  },

  // ---- 美國 ----
  {
    id: "us-nintendo-newyork", country: "美國", city: "紐約", name: "Nintendo NEW YORK",
    lat: 40.758062, lng: -73.979482, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅色照片鈕扣徽章飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "10 Rockefeller Plaza 場館座標", verificationStatus: "official",
    sourceTitle: "Pikmin Bloom Help Center — Special Spot", sourceUrl: officialHelp, lastVerifiedAt: verified2,
  },
  {
    id: "us-seattle-aquarium-pier59", country: "美國", city: "西雅圖", name: "西雅圖水族館 MINI WALK — Pier 59",
    lat: 47.607600, lng: -122.341400, spotKind: "limited", rewardKind: "gold_seedling",
    rewardSummary: "皮克敏金色花苗（對應各點裝飾，官方尚未公布明細）",
    startAt: seconds("2026-05-23T17:00:00Z"), endAt: seconds("2026-09-08T01:00:00Z"),
    cooldownNote: "每個 Special Spot 每 30 天最多 1 次", eligibilityNote: "活動期間西雅圖水族館本館（Pier 59）；5/23-25、9/5-7 另有快閃帳篷與 AR 拍照活動",
    coordinateNote: "官方公告列出「Pier 59、60 與 Ocean Pavilion」三處活動範圍，但尚未公布個別 Special Spot 座標（原文：a map featuring the Special Spots will be published at a later date）。此筆僅標示 Pier 59 場館座標作為範圍代表，官方稱共 9 個 Spot 分散在這三處附近，實際點位請以遊戲地圖或官方後續公布地圖為準，切勿以掃描或猜測座標取代",
    verificationStatus: "official",
    sourceTitle: "Seattle Aquarium MINI WALK 官方活動公告", sourceUrl: "https://pikminbloom.com/news/may26-seattleminiwalk", lastVerifiedAt: verified2,
  },
  {
    id: "us-seattle-aquarium-pier60", country: "美國", city: "西雅圖", name: "西雅圖水族館 MINI WALK — Pier 60",
    lat: 47.607900, lng: -122.341900, spotKind: "limited", rewardKind: "gold_seedling",
    rewardSummary: "皮克敏金色花苗（對應各點裝飾，官方尚未公布明細）",
    startAt: seconds("2026-05-23T17:00:00Z"), endAt: seconds("2026-09-08T01:00:00Z"),
    cooldownNote: "每個 Special Spot 每 30 天最多 1 次", eligibilityNote: "活動期間西雅圖水族館 Pier 60（新館）；5/23-25、9/5-7 另有快閃帳篷與 AR 拍照活動",
    coordinateNote: "同 Pier 59 條目：官方僅標示三處活動範圍，個別 Spot 座標未公布，此筆為 Pier 60 場館座標代表，請以遊戲地圖或官方地圖為準",
    verificationStatus: "official",
    sourceTitle: "Seattle Aquarium MINI WALK 官方活動公告", sourceUrl: "https://pikminbloom.com/news/may26-seattleminiwalk", lastVerifiedAt: verified2,
  },
  {
    id: "us-seattle-aquarium-ocean-pavilion", country: "美國", city: "西雅圖", name: "西雅圖水族館 MINI WALK — Ocean Pavilion",
    lat: 47.606700, lng: -122.342700, spotKind: "limited", rewardKind: "gold_seedling",
    rewardSummary: "皮克敏金色花苗（對應各點裝飾，官方尚未公布明細）",
    startAt: seconds("2026-05-23T17:00:00Z"), endAt: seconds("2026-09-08T01:00:00Z"),
    cooldownNote: "每個 Special Spot 每 30 天最多 1 次", eligibilityNote: "活動期間 Ocean Pavilion（水族館新館，Alaskan Way 對側）；5/23-25、9/5-7 另有快閃帳篷與 AR 拍照活動",
    coordinateNote: "同 Pier 59 條目：官方僅標示三處活動範圍，個別 Spot 座標未公布，此筆為 Ocean Pavilion 場館座標代表，請以遊戲地圖或官方地圖為準",
    verificationStatus: "official",
    sourceTitle: "Seattle Aquarium MINI WALK 官方活動公告", sourceUrl: "https://pikminbloom.com/news/may26-seattleminiwalk", lastVerifiedAt: verified2,
  },
  {
    id: "us-nintendo-sanfrancisco", country: "美國", city: "舊金山", name: "Nintendo SAN FRANCISCO",
    lat: 37.787780, lng: -122.408060, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅／黃／藍色禮物貼紙飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "331 Powell St 場館座標", verificationStatus: "official",
    sourceTitle: "Nintendo SAN FRANCISCO Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/may25-sfnintendo", lastVerifiedAt: verified2,
  },

  // ---- 台灣（永久 Special Spot，Nintendo 授權商品店） ----
  {
    id: "tw-shinkong-xinyi-a11", country: "台灣", city: "台北", name: "新光三越信義新天地 A11",
    lat: 25.033900, lng: 121.564500, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅／黃／藍色禮物貼紙飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "A11 館 Nintendo 授權商品店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "台灣 Nintendo 授權商品店新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/june25-taiwan", lastVerifiedAt: verified2,
  },
  {
    id: "tw-syntrend", country: "台灣", city: "台北", name: "三創生活園區 SYNTREND",
    lat: 25.047800, lng: 121.529000, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅／黃／藍色禮物貼紙飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "SYNTREND Nintendo 授權商品店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "台灣 Nintendo 授權商品店新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/june25-taiwan", lastVerifiedAt: verified2,
  },
  {
    id: "tw-lalaport-taichung", country: "台灣", city: "台中", name: "LaLaport 台中",
    lat: 24.147700, lng: 120.640300, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅／黃／藍色禮物貼紙飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "LaLaport 台中 Nintendo 授權商品店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "台灣 Nintendo 授權商品店新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/june25-taiwan", lastVerifiedAt: verified2,
  },
  {
    id: "tw-taipei-underground-software-world", country: "台灣", city: "台北", name: "台北地下街軟體世界",
    lat: 25.047800, lng: 121.517700, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅／黃／藍色禮物貼紙飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "台北地下街軟體世界店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "台灣 Nintendo 授權商品店新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/june25-taiwan", lastVerifiedAt: verified2,
  },
  {
    id: "tw-lalaport-nangang", country: "台灣", city: "台北", name: "LaLaport 南港",
    lat: 25.055900, lng: 121.616500, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅／黃／藍色禮物貼紙飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "LaLaport 南港 Nintendo 授權商品店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "台灣 Nintendo 授權商品店新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/june25-taiwan", lastVerifiedAt: verified2,
  },
  {
    id: "tw-dream-mall", country: "台灣", city: "高雄", name: "夢時代 Dream Mall",
    lat: 22.597700, lng: 120.300700, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅／黃／藍色禮物貼紙飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "夢時代 Nintendo 授權商品店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "台灣 Nintendo 授權商品店新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/june25-taiwan", lastVerifiedAt: verified2,
  },
  {
    id: "tw-hanshin-arena", country: "台灣", city: "高雄", name: "漢神巨蛋購物廣場",
    lat: 22.665600, lng: 120.301000, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅／黃／藍色禮物貼紙飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每 30 天最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "漢神巨蛋 Nintendo 授權商品店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "台灣 Nintendo 授權商品店新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/june25-taiwan", lastVerifiedAt: verified2,
  },

  // ---- 台灣（限時活動：IKEA x Pikmin Bloom，2026-08-01～08-31） ----
  {
    id: "tw-ikea-neihu", country: "台灣", city: "台北", name: "IKEA 內湖店",
    lat: 25.082600, lng: 121.587500, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "活動限定明信片＋工具皮克敏金色花苗（紅／黃／藍／紫／白／飛翼／岩石）；2000步挑戰另贈紅色照片鈕扣徽章金色花苗",
    startAt: seconds("2026-08-01T02:00:00Z"), endAt: seconds("2026-08-31T14:00:00Z"),
    cooldownNote: "每個 Special Spot 每 7 天最多 1 次；2000 步挑戰全活動限 1 次（不分店重複）", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準；活動期間店內同步舉辦 Pikmin 4 體驗",
    coordinateNote: "IKEA 內湖店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "IKEA x Pikmin Bloom 台灣限時活動官方公告", sourceUrl: "https://pikminbloom.com/news/august26-ikeatw", lastVerifiedAt: verified2,
  },
  {
    id: "tw-ikea-hsinchuang", country: "台灣", city: "新北", name: "IKEA 新莊店",
    lat: 25.036700, lng: 121.452000, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "活動限定明信片＋工具皮克敏金色花苗（紅／黃／藍／紫／白／飛翼／岩石）；2000步挑戰另贈紅色照片鈕扣徽章金色花苗",
    startAt: seconds("2026-08-01T02:00:00Z"), endAt: seconds("2026-08-31T14:00:00Z"),
    cooldownNote: "每個 Special Spot 每 7 天最多 1 次；2000 步挑戰全活動限 1 次（不分店重複）", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準；活動期間店內同步舉辦 Pikmin 4 體驗",
    coordinateNote: "IKEA 新莊店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "IKEA x Pikmin Bloom 台灣限時活動官方公告", sourceUrl: "https://pikminbloom.com/news/august26-ikeatw", lastVerifiedAt: verified2,
  },
  {
    id: "tw-ikea-xindian", country: "台灣", city: "新北", name: "IKEA 新店店",
    lat: 24.968000, lng: 121.539000, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "活動限定明信片＋工具皮克敏金色花苗（紅／黃／藍／紫／白／飛翼／岩石）；2000步挑戰另贈紅色照片鈕扣徽章金色花苗",
    startAt: seconds("2026-08-01T02:00:00Z"), endAt: seconds("2026-08-31T14:00:00Z"),
    cooldownNote: "每個 Special Spot 每 7 天最多 1 次；2000 步挑戰全活動限 1 次（不分店重複）", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準；活動期間店內同步舉辦 Pikmin 4 體驗",
    coordinateNote: "IKEA 新店店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "IKEA x Pikmin Bloom 台灣限時活動官方公告", sourceUrl: "https://pikminbloom.com/news/august26-ikeatw", lastVerifiedAt: verified2,
  },
  {
    id: "tw-ikea-taipei-arena", country: "台灣", city: "台北", name: "IKEA 台北城市店（小巨蛋）",
    lat: 25.051200, lng: 121.549300, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "活動限定明信片＋工具皮克敏金色花苗（紅／黃／藍／紫／白／飛翼／岩石）；2000步挑戰另贈紅色照片鈕扣徽章金色花苗",
    startAt: seconds("2026-08-01T02:00:00Z"), endAt: seconds("2026-08-31T14:00:00Z"),
    cooldownNote: "每個 Special Spot 每 7 天最多 1 次；2000 步挑戰全活動限 1 次（不分店重複）", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準；活動期間店內同步舉辦 Pikmin 4 體驗",
    coordinateNote: "IKEA 台北城市店（敦化北路）場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "IKEA x Pikmin Bloom 台灣限時活動官方公告", sourceUrl: "https://pikminbloom.com/news/august26-ikeatw", lastVerifiedAt: verified2,
  },
  {
    id: "tw-ikea-taoyuan", country: "台灣", city: "桃園", name: "IKEA 桃園店",
    lat: 24.993000, lng: 121.221000, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "活動限定明信片＋工具皮克敏金色花苗（紅／黃／藍／紫／白／飛翼／岩石）；2000步挑戰另贈紅色照片鈕扣徽章金色花苗",
    startAt: seconds("2026-08-01T02:00:00Z"), endAt: seconds("2026-08-31T14:00:00Z"),
    cooldownNote: "每個 Special Spot 每 7 天最多 1 次；2000 步挑戰全活動限 1 次（不分店重複）", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準；活動期間店內同步舉辦 Pikmin 4 體驗",
    coordinateNote: "IKEA 桃園店（中壢高鐵站前）場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "IKEA x Pikmin Bloom 台灣限時活動官方公告", sourceUrl: "https://pikminbloom.com/news/august26-ikeatw", lastVerifiedAt: verified2,
  },
  {
    id: "tw-ikea-taichung", country: "台灣", city: "台中", name: "IKEA 台中店",
    lat: 24.144500, lng: 120.639000, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "活動限定明信片＋工具皮克敏金色花苗（紅／黃／藍／紫／白／飛翼／岩石）；2000步挑戰另贈紅色照片鈕扣徽章金色花苗",
    startAt: seconds("2026-08-01T02:00:00Z"), endAt: seconds("2026-08-31T14:00:00Z"),
    cooldownNote: "每個 Special Spot 每 7 天最多 1 次；2000 步挑戰全活動限 1 次（不分店重複）", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準；活動期間店內同步舉辦 Pikmin 4 體驗",
    coordinateNote: "IKEA 台中店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "IKEA x Pikmin Bloom 台灣限時活動官方公告", sourceUrl: "https://pikminbloom.com/news/august26-ikeatw", lastVerifiedAt: verified2,
  },
  {
    id: "tw-ikea-chiayi", country: "台灣", city: "嘉義", name: "IKEA 嘉義城市店（大潤發嘉義店內）",
    lat: 23.475000, lng: 120.437000, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "活動限定明信片＋工具皮克敏金色花苗（紅／黃／藍／紫／白／飛翼／岩石）；2000步挑戰另贈紅色照片鈕扣徽章金色花苗",
    startAt: seconds("2026-08-01T02:00:00Z"), endAt: seconds("2026-08-31T14:00:00Z"),
    cooldownNote: "每個 Special Spot 每 7 天最多 1 次；2000 步挑戰全活動限 1 次（不分店重複）", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準；活動期間店內同步舉辦 Pikmin 4 體驗；本店為「店中店」型態，位於大潤發嘉義店內",
    coordinateNote: "IKEA 嘉義城市店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "IKEA x Pikmin Bloom 台灣限時活動官方公告", sourceUrl: "https://pikminbloom.com/news/august26-ikeatw", lastVerifiedAt: verified2,
  },
  {
    id: "tw-ikea-kaohsiung", country: "台灣", city: "高雄", name: "IKEA 高雄店",
    lat: 22.597800, lng: 120.303000, spotKind: "limited", rewardKind: "mixed",
    rewardSummary: "活動限定明信片＋工具皮克敏金色花苗（紅／黃／藍／紫／白／飛翼／岩石）；2000步挑戰另贈紅色照片鈕扣徽章金色花苗",
    startAt: seconds("2026-08-01T02:00:00Z"), endAt: seconds("2026-08-31T14:00:00Z"),
    cooldownNote: "每個 Special Spot 每 7 天最多 1 次；2000 步挑戰全活動限 1 次（不分店重複）", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準；活動期間店內同步舉辦 Pikmin 4 體驗",
    coordinateNote: "IKEA 高雄店場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "IKEA x Pikmin Bloom 台灣限時活動官方公告", sourceUrl: "https://pikminbloom.com/news/august26-ikeatw", lastVerifiedAt: verified2,
  },

  // ---- 香港（永久 Special Spot） ----
  {
    id: "hk-nsew-kmusea", country: "香港", city: "尖沙咀", name: "nsew — K11 MUSEA",
    lat: 22.294680, lng: 114.174150, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅色照片鈕扣徽章飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每日最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "K11 MUSEA B2/F Shop B211 場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "香港新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/dec25-hkspecialspots", lastVerifiedAt: verified2,
  },
  {
    id: "hk-nsew-kaitak", country: "香港", city: "九龍城", name: "nsew — 啟德體育園",
    lat: 22.321850, lng: 114.195300, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅色照片鈕扣徽章飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每日最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "啟德體育園 Kai Tak Mall 2 場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "香港新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/dec25-hkspecialspots", lastVerifiedAt: verified2,
  },
  {
    id: "hk-nsew-thewai", country: "香港", city: "大圍", name: "nsew — The Wai",
    lat: 22.372550, lng: 114.178720, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅色照片鈕扣徽章飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每日最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "The Wai 3/F Shop 314 場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "香港新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/dec25-hkspecialspots", lastVerifiedAt: verified2,
  },
  {
    id: "hk-assemble-hopewell", country: "香港", city: "灣仔", name: "Assemble — Hopewell Mall",
    lat: 22.277500, lng: 114.174500, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅色照片鈕扣徽章飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每日最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "Hopewell Mall 4/F Shop 414-415 場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "香港新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/dec25-hkspecialspots", lastVerifiedAt: verified2,
  },
  {
    id: "hk-lbuy-moko", country: "香港", city: "旺角", name: "LBuy — MOKO 新世紀廣場",
    lat: 22.322600, lng: 114.169100, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅色照片鈕扣徽章飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每日最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "MOKO 4/F Shop 426 場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "香港新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/dec25-hkspecialspots", lastVerifiedAt: verified2,
  },
  {
    id: "hk-nsew-hsr", country: "香港", city: "九龍", name: "nsew — 香港西九龍高鐵站",
    lat: 22.303700, lng: 114.162200, spotKind: "permanent", rewardKind: "gold_seedling",
    rewardSummary: "紅色照片鈕扣徽章飾品皮克敏金色花苗", startAt: 0, endAt: 0,
    cooldownNote: "每日最多 1 次", eligibilityNote: "需在 Special Spot 附近，並以遊戲顯示為準",
    coordinateNote: "西九龍站 nsew 場館座標；請以遊戲地圖確認", verificationStatus: "official",
    sourceTitle: "香港新增 Special Spot 官方公告", sourceUrl: "https://pikminbloom.com/en/news/dec25-hkspecialspots", lastVerifiedAt: verified2,
  },
];
